### ISSUE TITLE
KeyVal error

### ISSUE THREAD

**Issue by eyer** [redstreet/beancount_reds_plugins#14]
Receiving this error, but can't make sense of it. Can anyone help?

```
 File "/usr/local/lib/python3.7/site-packages/beancount_reds_plugins/effective_date/effective_date.py", line 118, in effective_date
    holding_account = holding_accts[found_acct]['earlier']
KeyError: ''
```

**Comment by redstreet** [comment]
Resolved [here](https://groups.google.com/g/beancount/c/mU5xtLkUxKc/m/IWJc1WCJAwAJ):
https://github.com/redstreet/beancount_reds_plugins/blob/master/beancount_reds_plugins/effective_date/examples.beancount

It'll fail that way if you're calling it for an account for which you haven't supplied a corresponding config.
