### ISSUE TITLE
Plain 'print' breaks CSV output

### ISSUE THREAD

**Issue by mmoya** [redstreet/beancount_reds_plugins#28]
This [print](/redstreet/beancount_reds_plugins/tree/main/beancount_reds_plugins/effective_date/effective_date.py#L51) breaks CSV output when using default config.

```
$ bean-query -f csv <(echo 'plugin "beancount_reds_plugins.effective_date.effective_date" ""') "SELECT *"
Using default config
date,flag,payee,narration,position
```

**Comment by redstreet** [comment]
Cool, thank you for filing. Any issues you see with printing to `stderr` instead?

**Comment by mmoya** [comment]
FTR, my workflow is:

```python
import subprocess
import petl as etl

stdout = subprocess.check_output(["bean-query", "-f", "csv", ...], stderr=subprocess.DEVNULL)
table = etl.fromcsv(etl.MemorySource(stdout))
```

So printing to `stderr` is fine but I don't know if it's better to use logging to allow controlling output from higher level or even not printing at all because default config is fine and well documented.

It took me a lot to find the cause of an `Using default config` in the middle of several ledger errors. Adding some context like `effective_date: Using default config` would help with troubleshooting.

Thanks.

**Comment by redstreet** [comment]
Thanks for the feedback: given the default config feels fine and documented, I'll remove it, and put it inside a `DEBUG` block, which is the stand in for logging I currently have. Done.
